baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://jerryzhen11.github.io/introduction/" # the base hostname & protocol for your site
root: /jerry-introduction

exclude:
    - "README.md"
    - "CHANGELOG.md"
    - "CNAME"
    - "Gemfile"
    - "Gemfile.lock"
